    ;do $System.OBJ.LoadDir("/opt/irisbuild/src","ck",,1)

    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    zn "USER"
    // install source control for Interoperability UI elements
    zpm "install git-source-control"
    do ##class(%Studio.SourceControl.Interface).SourceControlClassSet("SourceControl.Git.Extension")

    
    zpm "load /home/irisowner/irisdev/ -v":1:1
    halt
